FROM node:20-alpine AS build
WORKDIR /web
COPY client/package.json ./
RUN npm install
COPY client/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY deploy/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /web/dist /usr/share/nginx/html
EXPOSE 80
