{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-platform-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-platform-web
  template:
    metadata:
      labels:
        app: financial-platform-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: financial-platform-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: financial-platform-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
{{- end }}
